[package]
name = "rusty_clojure"
version = "0.1.0"
authors = ["ccQpein"]
edition = "2018"

[workspace]
members = [".", "parser", "generator"]

[dependencies]
parser = {path = "parser"}
generator = {path = "generator"}
